const CONFIG = {
  CANVAS_WIDTH: 360,
  CANVAS_HEIGHT: 640,
  GRAVITY: 0.26,
  JUMP_FORCE: -5.8,
  MAX_VELOCITY: 8,
  BIRD_X: 80,
  PIPE_WIDTH: 60,
  PIPE_GAP: 154,
  PIPE_SPAWN_DISTANCE: 220,
  WORLD_1_SPEED: 2.0,
  COIN_RADIUS: 11,
  BIRD_COLLISION_RADIUS: 14,
  REVIVE_COST: 1,
  FEVER_COIN_TARGET: 10,
  FEVER_DURATION: 300,
  PERFECT_PASS_WINDOW: 18,
  PERFECT_PASS_SCORE: 2,
  WORLD_UNLOCK_SCORE: 30,
  WORLD_2_UNLOCK_SCORE: 60,
  WORLD_3_UNLOCK_SCORE: 100
};

const I18N = {
  ar: {
    gameTitle: 'غضب الريش',
    gameSubtitle: 'انتقام الريش',
    startBtn: 'ابدأ المهمة',
    endlessBtn: 'الطور اللانهائي', reviveBtn: 'استمرار (محاولة ثانية)',
    tapToStart: 'انقر للطيران',
    tapToLaunch: 'انقر للتحطيم!', tapToContinue: 'انقر للمتابعة',
    pauseTitle: 'إيقاف مؤقت', resumeBtn: 'متابعة', restartBtn: 'إعادة', homeBtn: 'الرئيسية',
    shopTitle: 'متجر الأبطال', settingsTitle: 'الإعدادات', leaderboardTitle: 'لوحة الصدارة',
    soundEffects: 'المؤثرات الصوتية', music: 'الموسيقى', language: 'اللغة',
    resetProgress: 'حذف التقدم', returnBtn: 'عودة', buyBtn: 'شراء', equipBtn: 'استخدام', equippedBtn: 'مستخدم',
    owned: 'مملوك', locked: 'مقفل', ready: 'جاهز للعب!', worldLocked: 'عالم مقفل',
    world1: 'الأطلال', world2: 'الجليد', world3: 'العاصفة', world4: 'البركان',
    classicBird: 'العصفور الكلاسيكي',
    you: 'أنت',
    winTitle: 'انتصار!', winText: 'لقد أكملت الأطلال!', gameOverTitle: 'انتهت اللعبة',
    score: 'النقاط', best: 'الأفضل', coins: 'الكوينز',
    stage1: 'الأطلال القديمة', stage2: 'الغابة الملعونة',
    bossWarning: 'تحذير: الزعيم يقترب!',
    perfectPass: 'مرور مثالي!',
    fever: 'حمى الريش!',
    insufficientCoins: 'كوينز غير كافية'
  },
  en: {
    gameTitle: 'FEATHER FURY',
    gameSubtitle: 'Revenge of the Feathers',
    startBtn: 'START MISSION',
    endlessBtn: 'Endless Mode', reviveBtn: 'Continue (Revive)',
    tapToStart: 'TAP TO FLY',
    tapToLaunch: 'TAP TO SMASH!', tapToContinue: 'TAP TO CONTINUE',
    pauseTitle: 'PAUSED', resumeBtn: 'Resume', restartBtn: 'Restart', homeBtn: 'Home',
    shopTitle: 'Heroes Shop', settingsTitle: 'Settings', leaderboardTitle: 'Leaderboard',
    soundEffects: 'Sound Effects', music: 'Music', language: 'Language',
    resetProgress: 'Reset Progress', returnBtn: 'Return', buyBtn: 'Buy', equipBtn: 'Equip', equippedBtn: 'Equipped',
    owned: 'Owned', locked: 'Locked', ready: 'Ready to play!', worldLocked: 'Locked World',
    world1: 'Ruins', world2: 'Ice', world3: 'Storm', world4: 'Volcano',
    classicBird: 'Classic Bird',
    you: 'You',
    winTitle: 'VICTORY!', winText: 'You completed Ruins!', gameOverTitle: 'GAME OVER',
    score: 'Score', best: 'Best', coins: 'Coins',
    stage1: 'Ancient Ruins', stage2: 'Cursed Woods',
    bossWarning: 'WARNING: BOSS INCOMING!',
    perfectPass: 'PERFECT PASS!',
    fever: 'FEATHER FEVER!',
    insufficientCoins: 'Not enough coins'
  }
};