(()=>{
  const originalDrawBirdSkin = window.drawBirdSkin;
  window.__FF_ORIGINAL_DRAW_BIRD_SKIN__ = window.__FF_ORIGINAL_DRAW_BIRD_SKIN__ || originalDrawBirdSkin;
  let bootstrapReleased=false;
  const bootstrapGate=e=>{if(bootstrapReleased)return;if(e&&e.cancelable)e.preventDefault();e?.stopImmediatePropagation?.();};
  document.addEventListener('click',bootstrapGate,true);document.addEventListener('touchend',bootstrapGate,true);
  const releaseBootstrapGate=()=>{bootstrapReleased=true;document.removeEventListener('click',bootstrapGate,true);document.removeEventListener('touchend',bootstrapGate,true);};
  const legacyPatches=['ruins-pillars-v3.js?v=1','boss-crowking-v1.js?v=1','boss-fight-core-v1.js?v=1','w1-fixes-batch-v1.js?v=1','boss-audio-fix-v2.js?v=2','w1-final-audio-v1.js?v=1','w1-final-gameplay-v1.js?v=1','w1-final-story-v1.js?v=1','core-gameplay-ux-v1.js?v=3','pause-hud-polish-v2.js?v=1','world1-final-polish-v1.js?v=1','w2-audio-v1.js?v=1','w2-environment-assets-v1.js?v=3','w2-visuals-v1.js?v=4','w2-ice-ground-skeletons-v1.js?v=1','w2-gameplay-v1.js?v=1','revive-core-fix-v1.js?v=2','w2-emperor-art-v1.js?v=3','w2-boss-polish-v2.js?v=1','w2-boss-orb-v7.js?v=1','w2-boss-runtime-v10.js?v=1','victory-screen-fix-v1.js?v=1','w3-foundation-v1.js?v=1','w3-world-polish-v1.js?v=1','w3-boss-v1.js?v=1','w3-final-polish-v1.js?v=1','w3-balance-visual-v2.js?v=1','w3-challenge-audio-v3.js?v=1','w3-final-balance-v4.js?v=1','w3-critical-fix-v6.js?v=1','hero-blue-ninja-v1.js?v=2','hero-static-smooth-v2.js?v=1','hero-blue-effects-v1.js?v=3','fierce-falcon-v1.js?v=3','skin-routing-hardfix-v2.js?v=2','character-roster-v1.js?v=2','character-abilities-v2.js?v=2','mountain-eagle-stability-v3.js?v=1','character-ability-ui-v1.js?v=1','character-ability-fx-v1.js?v=1','world1-qa-fix-v2.js?v=1','owl-guardian-v2.js?v=2','world1-phase2-owl-dialogue-v3.js?v=2','world1-owl-dialogue-layer-fix-v3.js?v=1','crow-king-ingame-v4.js?v=1','crow-minions-ingame-v3.js?v=1','world1-crow-contrast-v1.js?v=1','world1-cursed-obstacle-asset-top-a.js?v=1','world1-cursed-obstacle-asset-bottom-a.js?v=2','world1-cursed-obstacles-v5.js?v=1','world1-classic-enhanced-background-v1.js?v=1','world1-ground-obstacle-polish-v2.js?v=3','w2-ice-ground-skeletons-v1.js?v=3'];
  function loadScript(src){return new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=src;s.onload=resolve;s.onerror=reject;document.head.appendChild(s);});}
  window.__FF_START_LEGACY_PATCH_CHAIN__=async()=>{for(const src of legacyPatches){try{await loadScript(src);}catch(e){console.warn('[FeatherFury] patch failed',src,e);}}};
  addEventListener('load',async()=>{await window.__FF_START_LEGACY_PATCH_CHAIN__();try{await loadScript('w2-emperor-crow-style-v4.js?v=4');}catch(e){console.warn('[FF] emperor v4 failed',e);}releaseBootstrapGate();});
})();